#!/usr/bin/env bash

# wait until the docker image exists
until docker history deis/slugrunner >/dev/null 2>&1; do
  sleep 2
done

# tag and push
docker tag deis/slugrunner:latest {{ getenv "DEIS_REGISTRY_SERVICE_HOST" }}:{{ getenv "DEIS_REGISTRY_SERVICE_PORT" }}/deis/slugrunner:latest
docker push {{ getenv "DEIS_REGISTRY_SERVICE_HOST" }}:{{ getenv "DEIS_REGISTRY_SERVICE_PORT" }}/deis/slugrunner:latest
